### PR TITLE
Add Unit Test Workflow

### PR DESCRIPTION
**Pull request by tylerbwong**

### CODE REVIEW

**Comment by tylerbwong** [comment]
@doodla Looks like tests are failing on 3.7. Is this a real issue or should I just remove 3.7 from the matrix?

**Comment by doodla** [comment]
I can't see the logs. What's the error?

**Comment by tylerbwong** [comment]
> I can't see the logs. What's the error?

```
==================================== ERRORS ====================================
____________________ ERROR collecting tests/test_models.py _____________________
ImportError while importing test module '/home/runner/work/octohook/octohook/tests/test_models.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_models.py:3: in <module>
    from typing import get_type_hints, get_origin, get_args
E   ImportError: cannot import name 'get_origin' from 'typing' (/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/typing.py)
=========================== short test summary info ============================
ERROR tests/test_models.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.[23](https://github.com/doodla/octohook/runs/5984035784?check_suite_focus=true#step:6:23)s ===============================
```

Looks like some test import isn't available in this version of Python. I guess for now remove?

**Comment by doodla** [comment]
Yeah, let's remove it for now. Thanks for adding tests!

**Pull request merged**
